"""Local Ollama provider for the Resume Copilot (Phase 7A).

This provider:
- communicates only with a localhost Ollama instance via stdlib urllib,
- never exposes a prompt, response content, or any PII in logs/metadata,
- returns structured responses via ``parse_llm_json`` and raises
  ``CopilotError`` subclasses on any failure (so the orchestrator can
  gracefully degrade).

No new dependencies are introduced.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Any

from app.copilot.config import (
    COPILOT_DISCLAIMER,
    COPILOT_IMPLEMENTATION_VERSION,
    CopilotSettings,
    copilot_settings,
)
from app.copilot.errors import (
    MalformedProviderOutputError,
    ProviderTimeoutError,
    ProviderUnavailableError,
)
from app.copilot.operations import get_contract
from app.copilot.prompting import (
    build_messages,
    llm_suggestion_to_contract,
    parse_llm_json,
)
from app.copilot.schemas import (
    CopilotRequest,
    CopilotResponse,
    ProviderKind,
    ProviderMetadata,
)
from app.copilot.validation import validate_llm_suggestions


class LocalOllamaProvider:
    """Generative provider that talks to a local Ollama instance."""

    def __init__(self, settings: CopilotSettings | None = None) -> None:
        self._settings = settings or copilot_settings

    # ------------------------------------------------------------------
    # Provider protocol
    # ------------------------------------------------------------------

    def provider_kind(self) -> ProviderKind:
        return ProviderKind.LOCAL_OLLAMA

    def available(self) -> bool:
        """Return True when Ollama is reachable and has the target model.

        Failures are caught and reported as ``False`` — never raised.
        """
        if not self._settings.llm_enabled:
            return False
        try:
            data = self._request(
                "/api/tags",
                method="GET",
                timeout_seconds=self._settings.llm_availability_timeout_seconds,
            )
            models = [m.get("name", "") for m in data.get("models", [])]
            target = self._settings.ollama_model
            return any(
                model == target or model.startswith(target + ":") for model in models
            )
        except Exception:
            return False

    def supports(self, request: CopilotRequest) -> bool:
        """True when the LLM is enabled and the operation is generative."""
        if not self._settings.llm_enabled:
            return False
        contract = get_contract(request.operation)
        return contract.fallback_available

    def metadata(self, available: bool | None = None) -> ProviderMetadata:
        """Return safe provider metadata.

        ``available`` overrides the live check for callers that are already
        mid-execution (e.g. ``run``), avoiding a redundant network probe.
        """
        return ProviderMetadata(
            provider=ProviderKind.LOCAL_OLLAMA,
            provider_label=f"Local Ollama ({self._settings.ollama_model})",
            model=self._settings.ollama_model,
            available=self.available() if available is None else available,
            fallback_used=False,
            version=COPILOT_IMPLEMENTATION_VERSION,
            note=(
                "Responses are generated by a local Ollama model using the "
                "structured data provided. Facts are not invented."
            ),
        )

    def run(self, request: CopilotRequest) -> CopilotResponse:
        """Execute the request against Ollama and return a validated response.

        Raises ``ProviderTimeoutError``, ``ProviderUnavailableError``, or
        ``MalformedProviderOutputError`` on any failure.
        """
        messages = build_messages(request, self._settings)
        body: dict[str, Any] = {
            "model": self._settings.ollama_model,
            "messages": messages,
            "format": "json",
            "stream": False,
            "options": {"num_predict": self._settings.llm_max_tokens},
        }
        try:
            raw = self._request(
                "/api/chat",
                method="POST",
                body=body,
                timeout_seconds=self._settings.llm_request_timeout_seconds,
            )
        except TimeoutError:
            raise ProviderTimeoutError(
                "Ollama timed out while generating the Copilot response."
            ) from None
        except urllib.error.URLError as exc:
            raise ProviderUnavailableError(
                f"Ollama is unreachable: {exc.reason}"
            ) from exc
        except urllib.error.HTTPError as exc:
            raise ProviderUnavailableError(f"Ollama returned HTTP {exc.code}.") from exc

        if not isinstance(raw, dict):
            raise MalformedProviderOutputError("Ollama returned a non-object response.")
        message = raw.get("message")
        if not isinstance(message, dict):
            raise MalformedProviderOutputError(
                "Ollama response is missing the 'message' object."
            )
        content = message.get("content", "")
        if not isinstance(content, str) or not content.strip():
            raise MalformedProviderOutputError(
                "Ollama response message content is empty or not a string."
            )

        parsed = parse_llm_json(content)
        operation = request.operation
        max_suggestions = self._settings.max_suggestions

        suggestions = [
            llm_suggestion_to_contract(
                {
                    "category": item.get("category", "clarity"),
                    "original_text": _string(item.get("original_text")),
                    "suggested_text": _string(item.get("suggested_text")),
                    "rationale": _string(item.get("rationale")),
                    "evidence": [
                        {
                            "kind": _string(ev.get("kind", "suggestion")),
                            "source": _string(ev.get("source", "copilot.inference")),
                            "statement": _string(ev.get("statement", "")),
                            "reference": _string(ev.get("reference", "")),
                        }
                        for ev in item.get("evidence", [])
                    ],
                    "verification": _string(item.get("verification", "unverified")),
                    "requires_user_confirmation": bool(
                        item.get("requires_user_confirmation", False)
                    ),
                },
                suggestion_id=f"sug_{idx + 1}",
                operation=operation,
            )
            for idx, item in enumerate(parsed.get("suggestions", [])[:max_suggestions])
            if isinstance(item, dict)
        ]
        # Factual/evidence validation: anything not traceable to the supplied
        # materials is downgraded to a confirmation-required suggestion.
        suggestions = validate_llm_suggestions(request, suggestions)

        explanation = _string(
            parsed.get(
                "explanation",
                f"Ollama generated Copilot suggestions for '{operation.value}'.",
            )
        )

        if not suggestions:
            raise MalformedProviderOutputError(
                "Ollama returned a valid JSON shape but zero suggestions."
            )

        return CopilotResponse(
            operation=operation,
            explanation=explanation,
            suggestions=suggestions,
            provider=self.metadata(available=True),
            disclaimer=COPILOT_DISCLAIMER,
        )

    # ------------------------------------------------------------------
    # HTTP helpers
    # ------------------------------------------------------------------

    def _request(
        self,
        path: str,
        *,
        method: str,
        body: dict[str, Any] | None = None,
        timeout_seconds: float,
    ) -> Any:
        """Send an HTTP request to Ollama and return the parsed JSON body.

        Raises urllib exceptions on network/timeout errors.
        """
        url = self._settings.ollama_base_url.rstrip("/") + path
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(
            url,
            data=data,
            method=method,
            headers={"Accept": "application/json", "Content-Type": "application/json"}
            if data
            else {"Accept": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=timeout_seconds) as resp:
            return json.loads(resp.read().decode("utf-8"))


def _string(value: object) -> str:
    """Coerce a JSON value to string, returning '' on None."""
    if value is None:
        return ""
    return str(value).strip()
